fix: allow shipping international orders when mailbox is default
myparcelnl/shopware6 pull request #34
Opened 2023-06-22 16:05 UTC by joerivanveen

2023-06-26 08:16 UTC, Mark-Ernst approved these changes

2023-06-29 12:20 UTC, EdieLemoine requested changes

2023-06-29 12:20 UTC, EdieLemoine commented on src/Service/Config/ScriptService.php
> +    public function getDeliveryOptionsCdnUrl() {
geen return types(?)

2023-06-29 12:20 UTC, EdieLemoine commented on src/Service/Config/ScriptService.php
> +        return '5.8.0';
we zitten op 5.9.0 

https://github.com/myparcelnl/delivery-options/releases

Wat je ook kan doen is met unpkg automatisch de laatste versie op major 5 pakken:

> `<package>@^5`

Mocht je dat willen doen... Let er wel op dat de `^` url encoded moet zijn, gebeurt niet altijd vanzelf

2023-06-29 12:20 UTC, EdieLemoine commented on src/Service/Config/ConfigGenerator.php
> +        if (0 !== strpos($field, 'allow')) {
Heeft deze plugin de sdk niet? Indien "jawel", gebruik `Str::startsWith()` :)

2023-06-29 12:20 UTC, EdieLemoine commented on src/Service/Config/ConfigGenerator.php
> +        $settings['allowDeliveryOptions'] = true;
als dit toch altijd true is, zet hem dan bovenaan in de initialisatie van $settings

2023-06-29 12:20 UTC, EdieLemoine commented on src/Service/Config/ConfigGenerator.php
> +        }
ik ben niet gemotiveerd om op dit moment heel moeilijk te doen qua code style, maar geef blocks aub wat ruimte 🙏🏼

2023-07-07 09:05 UTC, EdieLemoine approved these changes

2023-07-07 09:06 UTC, merged